AllCops:
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Max: 100

Metrics/AbcSize:
  Max: 15

Metrics/MethodLength:
  Max: 10

Metrics/LineLength:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/ModuleLength:
  Max: 100

Metrics/BlockLength:
  Max: 25

Metrics/BlockNesting:
  Max: 3

Metrics/ParameterLists:
  Max: 5

Metrics/PerceivedComplexity:
  Max: 7
